### ISSUE TITLE
Update on the readme disclaimer. 

### ISSUE THREAD

**Issue by alexcroox** [pimlie/nuxt-lambda#14]
Love your work here. I’ve faced some real challenges getting a SSR app into lambda due to size constraints then the hot mess of what goes in dev or normal deps to keep the size under 50mb. Bundling it up seems the right way to go even if you do lose out on some runtime properties. 

The top of your readme states you were waiting for updates to Nuxt core before bringing under the @nuxt banner. Is that still the plan? What was the blocker?

Thanks!

**Comment by pimlie** [comment]
@alexcroox Hey, no its not the plan anymore to bring this code under the nuxt umbrella. I should update the readme probably.
Nuxt is working on a new & improved solution thats much more generic then this project. You can check the demo for it here: https://github.com/nuxt/sigma-demo

Btw. getting your project under 50MB should be fairly easy. If you'd use this package then I recommend adding the following config:
```js
      excludeFiles: (filePath) => filePath.endsWith('.map'),
      excludeClientFiles: ['img/', 'fonts/', 'videos/'],
```

This will ensure that your static files wont be included in the lambda

**Comment by alexcroox** [comment]
Thanks for the update, I'm currently experimenting with their undocumented --standalone build mode.

Re: the issue of size, I don't have any assets, it's more larger node_modules it was bringing over which aren't tree-shaken server side, e.g Sentry being 20MB alone. (this is without using this lib ofc).

I will keep an eye on sigma thank you!
